// app/components/Banner.tsx
export default function Banner({ title, description }: { title: string; description?: string }) {
	return (
		<header
			className='m-4 mb-8 p-12 text-center rounded-2xl shadow-xl relative'
			style={{
				color: 'var(--dark-green)',
				backgroundColor: 'var(--green)',
				borderRadius: '1rem 8rem',
			}}
		>
			<div
				id='leaf'
				className='absolute aspect-square z-0 top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2'
				style={{
					height: 'calc(100% - 2rem)',
					backgroundColor: 'var(--background)',
					borderRadius: '0 100%',
				}}
			>
			</div>
			<h1 className='text-4xl font-bold relative z-10'>{title}</h1>
			{description && <p className='relative z-10'>{description}</p>}
		</header>
	);
}

// frontend/src/components/Banner.svelte
<script lang="ts">
	let { title, description }: { title: string; description?: string | null } =
		$props();
</script>

<header>
	<div id="leaf"></div>
	<h1>{title}</h1>
	{#if description}<p>{description}</p>{/if}
</header>

<style>
	header {
		margin: 1rem 1rem 2rem;
		padding: 3rem;
		color: var(--dark-green);
		background-color: var(--green);
		text-align: center;
		border-radius: 1rem 8rem;
		box-shadow: 0 0 1rem rgba(0, 0, 0, 0.2);
		position: relative;
	}

	header h1 {
		font-size: 2.5rem;
		font-weight: bold;
	}

	header :is(p, h1) {
		position: relative;
		z-index: 1;
	}

	#leaf {
		height: calc(100% - 2rem);
		aspect-ratio: 1 / 1;
		position: absolute;
		z-index: 0;
		inset: 50%;
		transform: translate(-50%, -50%);
		background-color: var(--background);
		border-radius: 0 100%;
	}
</style>
