// app/components/EventCard.tsx
import { Tables } from '$lib/models.ts';
import { formatDate } from '$lib/utils.ts';

export default function EventCard({ event }: { event: Tables<'upcoming_events'> }) {
	return (
		<div className="grid grid-cols-[250px_1fr_auto] items-center md:max-w-[900px]:grid-cols-[1fr_2fr] md:max-w-[900px]:grid-rows-[auto_auto] md:max-w-[900px]:[grid-template-areas:'image_details'_'image_register'] max-sm:grid-cols-1 border-2 border-[var(--foreground)] rounded-2xl shadow-[0_0_1rem_rgba(0,0,0,0.2)]">
			<div
				className='w-full h-full rounded-l-2xl bg-center bg-no-repeat bg-cover md:max-w-[900px]:[grid-area:image] max-sm:rounded-t-2xl max-sm:rounded-l-none'
				style={{ backgroundImage: `url(${event.image})`, aspectRatio: '16/9' }}
			/>
			<div className='p-4 md:max-w-[900px]:[grid-area:details]'>
				<h2 className='text-2xl font-bold line-clamp-2 text-ellipsis'>{event.title}</h2>
				<p>
					<span className='material-symbols-rounded relative' style={{ top: '0.3rem' }}>event</span>{' '}
					<strong>Date:</strong> {event.start_time ? formatDate(event.start_time) : 'N/A'} &ndash;{' '}
					{event.end_time ? formatDate(event.end_time) : 'N/A'}
				</p>
				<p>
					<span className='material-symbols-rounded relative' style={{ top: '0.3rem' }}>location_on</span>
					{' '}
					<strong>Location:</strong> {event.location}
				</p>
			</div>
			<div className='p-4 md:max-w-[900px]:[grid-area:register] md:max-w-[900px]:self-start max-sm:pt-0'>
				<a className='cta' href={`/events/${event.id}`}>Register</a>
			</div>
		</div>
	);
}

// frontend/src/components/EventCard.svelte
<script lang="ts">
	import type { Tables } from "$lib/models";
	import { formatDate } from "$lib/utilities";

	let { event }: { event: Tables<"upcoming_events"> } = $props();
</script>

<div class="event">
	<div class="image" style="--src: url({event.image})"></div>
	<div class="details">
		<h2>{event.title}</h2>
		<p>
			<span class="material-symbols-rounded">event</span>
			<strong>Date:</strong>
			{event.start_time ? formatDate(event.start_time) : "N/A"} &ndash;
			{event.end_time ? formatDate(event.end_time) : "N/A"}
		</p>
		<p>
			<span class="material-symbols-rounded">location_on</span>
			<strong>Location:</strong>
			{event.location}
		</p>
	</div>
	<div class="register">
		<a class="cta" href="/events/{event.id}">Register</a>
	</div>
</div>

<style>
	.event {
		display: grid;
		align-items: center;
		grid-template-columns: 1fr 3fr auto;
		border: 2px solid var(--foreground);
		border-radius: 1rem;
		box-shadow: 0 0 1rem rgba(0, 0, 0, 0.2);
	}

	.event .image {
		width: 100%;
		height: 100%;
		aspect-ratio: 16 / 9;
		border-radius: 1rem 0 0 1rem;
		background-image: var(--src);
		background-position: center;
		background-repeat: no-repeat;
		background-size: cover;
	}

	.event :where(.details, .register) {
		padding: 1rem;
	}

	/* Medium screen layout */
	@media (width <= 900px) and (width > 640px) {
		.event {
			grid-template-columns: 1fr 2fr;
			grid-template-rows: auto auto;
			grid-template-areas: "image details" "image register";
		}
		.event .image {
			grid-area: image;
		}
		.event .details {
			grid-area: details;
		}
		.event .register {
			grid-area: register;
			align-self: start;
		}
	}

	@media (width <= 640px) {
		.event {
			grid-template-columns: 1fr;
		}

		.event .image {
			border-radius: 1rem 1rem 0 0;
		}

		.event .register {
			padding-top: 0;
		}
	}
</style>
