// app/components/Footer.tsx
import { Leaf } from './Leaf.tsx';

/**
 * Explore - Links to internal ITea Lab sections
 */
const explore = [
	{ name: 'About', href: '/' },
	{ name: 'Community', href: '/' },
	{ name: 'Join Us', href: '/' },
];

/**
 * Community - Links to external ITea Lab social media
 */
const community = [
	{ name: 'GitHub', href: 'https://github.com/itea-lab' },
	{ name: 'Facebook', href: 'https://facebook.com/ITeaLabTeam/' },
	{ name: 'LinkedIn', href: 'https://linkedin.com/company/itea-lab' },
];

/**
 * Contact - Contact information for ITea Lab
 */
const contact = {
	email: 'contact.itealab@gmail.com',
	address: 'A35 Bach Dang street, Tan Binh district, Ho Chi Minh city, Vietnam',
};

export function Footer() {
	return (
		<footer className='mt-8 overflow-hidden bg-(--green)'>
			<div
				id='curve'
				className='h-12 bg-(--background)'
				style={{ borderRadius: '0 0 100% 100%' }}
			/>
			<section
				id='menu'
				className='mx-12 p-8 flex items-baseline justify-around relative flex-wrap md:flex-nowrap md:p-8'
			>
				<div className='mx-0 md:mx-4 flex-grow-0 text-center md:text-left'>
					<h1 className='text-3xl font-bold'>ITea Lab</h1>
					<p>Where tech meets its quali-tea</p>
				</div>
				<div className='mx-0 md:mx-4 flex-grow-0 text-center md:text-left'>
					<h2 className='text-2xl font-bold'>Explore</h2>
					{explore.map((item) => (
						<p>
							<a href={item.href}>{item.name}</a>
						</p>
					))}
				</div>
				<div className='mx-0 md:mx-4 flex-grow-0 text-center md:text-left'>
					<h2 className='text-2xl font-bold'>Community</h2>
					{community.map((item) => (
						<p>
							<a href={item.href} target='_blank' rel='noopener noreferrer'>
								{item.name}
							</a>
						</p>
					))}
				</div>
				<div className='mx-0 md:mx-4 flex-grow-0 text-center md:text-left w-full md:w-3/5'>
					<h2 className='text-2xl font-bold'>Contact</h2>
					<p>
						<a href={`mailto:${contact.email}`}>{contact.email}</a>
					</p>
					<p id='address' className='md:w-3/5'>{contact.address}</p>
				</div>
				<div
					id='leaf'
					className='static md:absolute md:bottom-0 md:-right-40 md:w-80 md:h-60 md:overflow-hidden md:z-0'
				>
					<Leaf />
				</div>
			</section>
		</footer>
	);
}

// frontend/src/components/Footer.svelte
<script lang="ts">
	import Leaf from "./Leaf.svelte";

	/**
	 * Explore - Links to internal ITea Lab sections
	 */
	const explore = [
		{ name: "About", href: "/" },
		{ name: "Community", href: "/" },
		{ name: "Join Us", href: "/" },
	];

	/**
	 * Community - Links to external ITea Lab social media
	 */
	const community = [
		{ name: "GitHub", href: "https://github.com/itea-lab" },
		{ name: "Facebook", href: "https://facebook.com/ITeaLabTeam/" },
		{ name: "LinkedIn", href: "https://linkedin.com/company/itea-lab" },
	];

	/**
	 * Contact - Contact information for ITea Lab
	 */
	const contact = {
		email: "contact.itealab@gmail.com",
		address:
			"A35 Bach Dang street, Tan Binh district, Ho Chi Minh city, Vietnam",
	};
</script>

<footer>
	<div id="curve"></div>
	<section id="menu">
		<div>
			<h1>ITea Lab</h1>
			<p>Where tech meets its quali-tea</p>
		</div>
		<div>
			<h2>Explore</h2>
			{#each explore as item}
				<p><a href={item.href}>{item.name}</a></p>
			{/each}
		</div>
		<div>
			<h2>Community</h2>
			{#each community as item}
				<p>
					<a
						target="_blank"
						rel="noopener noreferrer"
						href={item.href}
					>
						{item.name}
					</a>
				</p>
			{/each}
		</div>
		<div>
			<h2>Contact</h2>
			<p>
				<a href="mailto:{contact.email}">{contact.email}</a>
			</p>
			<p id="address">{contact.address}</p>
		</div>
		<div id="leaf">
			<Leaf />
		</div>
	</section>
</footer>

<style>
	footer {
		margin-top: 2rem;
		background-color: var(--green);
		overflow: hidden;
	}

	#curve {
		height: 3rem;
		background-color: var(--background);
		border-radius: 0 0 100% 100%;
	}

	#menu {
		margin-inline: 3rem;
		padding: 2rem;
		display: flex;
		align-items: first baseline;
		justify-content: space-around;
		position: relative;
	}

	#menu > div {
		margin-inline: 1rem;
		flex-grow: 0;
	}

	#address {
		width: 60%;
	}

	#leaf {
		width: 20rem;
		height: 15rem;
		bottom: 0;
		right: -10rem;
		position: absolute;
		overflow: hidden;
		z-index: 0;
	}

	@media (max-width: 768px) {
		#menu {
			padding: 1rem;
			padding-bottom: 0;
			flex-wrap: wrap;
		}

		#menu > div {
			margin-inline: 0;
			text-align: center;
		}

		#address {
			width: 100%;
		}

		#leaf {
			position: static;
		}
	}
</style>
