// webapp/src/components/Banner.svelte
<script lang="ts">
	export let title: string = "Title";
	export let description: string | null = null;
</script>

<header>
	<h1>{title}</h1>
	{#if description}<p>{description}</p>{/if}
</header>

<style>
	header {
		margin-bottom: 2rem;
		padding: 2rem;
		background-color: var(--dark-green);
		color: var(--green);
		text-align: center;
	}

	header h1 {
		font-size: 2.5rem;
		font-weight: bold;
	}
</style>

// app/components/Banner.tsx
export default function Banner({ title, description }: { title: string; description?: string }) {
	return (
		<header
			className='m-4 mb-8 p-12 text-center rounded-2xl shadow-xl relative'
			style={{
				color: 'var(--dark-green)',
				backgroundColor: 'var(--green)',
				borderRadius: '1rem 8rem',
			}}
		>
			<div
				id='leaf'
				className='absolute aspect-square z-0 top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2'
				style={{
					height: 'calc(100% - 2rem)',
					backgroundColor: 'var(--background)',
					borderRadius: '0 100%',
				}}
			>
			</div>
			<h1 className='text-4xl font-bold relative z-10'>{title}</h1>
			{description && <p className='relative z-10'>{description}</p>}
		</header>
	);
}
