// frontend/src/components/Navbar.svelte
<header class="navbar">
	<a class="brand" href="/">
		<img src="/logos/logo.svg" alt="Tradao Logo" />
	</a>
	<nav>
		<a href="/manage">
			<span class="material-symbols-rounded">manage_accounts</span>
			Manage
		</a>
	</nav>
</header>

<style>
	.navbar {
		padding: 1rem 2rem;
		display: flex;
		align-items: center;
		justify-content: space-between;
	}

	.navbar .brand:hover {
		scale: 1.1;
	}

	.navbar .brand img {
		height: 4rem;
	}

	.navbar nav {
		display: flex;
		gap: 1rem;
	}

	.material-symbols-rounded {
		position: relative;
		top: 0.2em;
	}
</style>

// app/components/Navbar.tsx
import { TextClock } from '$islands/TextClock.tsx';

interface NavbarProps {
	menuItems: {
		name: string;
		href: string;
		icon: string;
		external: boolean;
	}[];
}

export function Navbar({ menuItems }: NavbarProps) {
	return (
		<header className='flex flex-col md:flex-row items-center justify-between px-8 py-4 gap-4'>
			<a className='hover:scale-110' href='/'>
				<img
					src='/logos/logo.svg'
					alt='Tradao Logo'
					style={{ height: '4rem' }}
				/>
			</a>
			<nav className='flex flex-row flex-wrap gap-2 justify-center md:items-center'>
				<TextClock />
				<span className='hidden md:inline'>|</span>
				{menuItems.map((item) => (
					<a
						className='hover:scale-110'
						key={item.name}
						href={item.href}
						target={item.external ? '_blank' : '_self'}
						rel={item.external ? 'noopener noreferrer' : ''}
					>
						<span className='material-symbols-rounded relative top-[0.3rem]'>
							{item.icon}
						</span>{' '}
						{item.name}
					</a>
				))}
			</nav>
		</header>
	);
}
