// app/components/Banner.tsx
import { BannerProps } from '$lib/props.ts';

export function Banner({ title, description }: BannerProps) {
	return (
		<header className='large-padding'>
			<div className='space'></div>

			<h1 className='small center-align'>{title}</h1>
			{description && <p className='large-text center-align'>{description}</p>}

			<div className='space'></div>
		</header>
	);
}

// app/src/components/Banner.svelte
<script lang="ts">
	import type { BannerProps } from '$lib/props';

	let { title, description }: BannerProps = $props();
</script>

<header class="large-padding transparent">
	<div class="space"></div>

	<h1 class="small center-align">{title}</h1>
	{#if description}
		<p class="large-text center-align">{description}</p>
	{/if}

	<div class="space"></div>
</header>
