// app/routes/tickets/[id].tsx
import { define, formatDate } from '$lib/utils.ts';
import { TicketLookupProps } from '$lib/props.ts';
import { supabase } from '$lib/supabase.ts';
import { PageTitle } from '$components/PageTitle.tsx';
import { Banner } from '$components/Banner.tsx';

export const handler = define.handlers<TicketLookupProps>({
	async GET(ctx) {
		const ticketID = ctx.params.id;

		const { data, error: err } = await supabase
			.functions.invoke(`get-ticket?ticketID=${ticketID}`, {
				method: 'GET',
				headers: {},
			});

		if (err) throw err;

		return { data: data ?? [] };
	},
});

function TicketHeader({ props }: { props: TicketLookupProps }) {
	return <h2 className='text-2xl text-center font-bold'>{props.lookup.event_title}</h2>;
}

function TicketDetails({ props }: { props: TicketLookupProps }) {
	return (
		<dl className='grid gap-2 gap-x-4' style={{ gridTemplateColumns: 'auto auto' }}>
			<dt className='font-bold text-right'>Name</dt>
			<dd>{props.lookup.name}</dd>
			<dt className='font-bold text-right'>Email</dt>
			<dd>{props.lookup.email}</dd>
			<dt className='font-bold text-right'>Academic Year</dt>
			<dd>{props.lookup.academic_year}</dd>
			<dt className='font-bold text-right'>Field of Study</dt>
			<dd>{props.lookup.field_of_study}</dd>
			<dt className='font-bold text-right'>Major</dt>
			<dd>{props.lookup.major}</dd>
			<dt className='font-bold text-right'>Participating</dt>
			<dd>{props.lookup.participate ? 'Yes' : 'No'}</dd>
			<dt className='font-bold text-right'>Created At</dt>
			<dd>{formatDate(props.lookup.created_at!)}</dd>
		</dl>
	);
}

function TicketFooter({ props }: { props: TicketLookupProps }) {
	return (
		<section id='footer' className='text-center'>
			<a href={props.saveURL} id='save-button' target='_blank' rel='noopener noreferrer'>
				<img
					src='/buttons/enAU_add_to_google_wallet_add-wallet-badge.svg'
					alt='Add to Google Wallet'
					className='mx-auto'
				/>
			</a>
			<p>{props.lookup.ticket_id}</p>
		</section>
	);
}

export default define.page<typeof handler>(function TicketLookupPage(props) {
	return (
		<>
			<PageTitle title={'Your Ticket for ' + props.data.lookup.event_title} />

			<Banner title='Here is your event ticket!' />
			<div className='p-4'>
				<article
					className='max-w-[90ch] mx-auto p-4 border-2 rounded-2xl relative'
					style={{ borderColor: 'var(--foreground)' }}
				>
					<TicketHeader props={props.data} />
					<hr className='my-4 border rounded-2xl border-[--foreground]' />
					<TicketDetails props={props.data} />
					<hr className='my-4 border rounded-2xl border-[--foreground]' />
					<TicketFooter props={props.data} />
				</article>
			</div>
		</>
	);
})

// frontend/src/routes/tickets/[id]/+page.svelte
<script lang="ts">
	import Banner from "$components/Banner.svelte";
	import Title from "$components/Title.svelte";
	import type { Tables } from "$lib/models";

	let {
		data,
	}: {
		data: {
			lookup: Tables<"tickets_with_event_details">;
			saveURL: string;
		};
	} = $props();
</script>

<Title title={"Your ticket for " + data.lookup.event_title} />

<Banner title="Here is your event ticket!" />

<div>
	<article>
		<h2>{data.lookup.event_title}</h2>
		<hr />
		<dl>
			<dt>Name</dt>
			<dd>{data.lookup.name}</dd>
			<dt>Email</dt>
			<dd>{data.lookup.email}</dd>
			<dt>Academic Year</dt>
			<dd>{data.lookup.academic_year}</dd>
			<dt>Field of Study</dt>
			<dd>{data.lookup.field_of_study}</dd>
			<dt>Major</dt>
			<dd>{data.lookup.major}</dd>
			<dt>Participating</dt>
			<dd>{data.lookup.participate ? "Yes" : "No"}</dd>
			<dt>Created At</dt>
			<dd>{data.lookup.created_at}</dd>
		</dl>
		<hr />
		<section id="footer">
			<a href={data.saveURL} id="save-button" target="_blank" rel="noopener noreferrer">
				<img
					src="/enAU_add_to_google_wallet_add-wallet-badge.svg"
					alt="Add to Google Wallet"
				/>
			</a>
			<p>{data.lookup.ticket_id}</p>
		</section>
	</article>
</div>

<style>
	div {
		padding: 1rem;
	}

	article {
		max-width: 90ch;
		margin: auto;
		padding: 1rem;
		border: 2px solid var(--foreground);
		border-radius: 1rem;
		position: relative;
	}

	article h2 {
		text-align: center;
	}

	article hr {
		margin-block: 1rem;
		border: 1px solid var(--foreground);
		border-radius: 1rem;
	}

	article section#footer {
		text-align: center;
	}

	dl {
		display: grid;
		gap: 0.5rem 1rem;
		grid-template-columns: auto auto;
	}

	dt {
		font-weight: bold;
		text-align: end;
	}

	dd {
		margin: 0;
	}
</style>
