// app/src/routes/manage/+page.svelte
<script lang="ts">
	import PageMetadata from "$components/PageMetadata.svelte";
	import Banner from "$components/Banner.svelte";
	import type { PageData } from "./$types";

	let { data }: { data: PageData } = $props();
	let username = $derived(data.user?.email ?? "User");
</script>

<PageMetadata
	title="Management Home"
	description="Manage ITea Lab events and Tradao tickets here"
	keywords="ITea Lab, Tradao, Management Dashboard, Events, Tickets, Technology, Innovation, Community, Vietnam"
/>

<Banner
	title={`Welcome back, ${username}`}
	description="Manage ITea Lab events and Tradao tickets here"
/>

<section style="max-width: 90ch; margin: auto">
	<a class="block" href="/manage/events">
		<article>
			<h2><i>event</i> Manage Events</h2>
			<div class="row right-align">
				<i>arrow_forward</i>
			</div>
		</article>
	</a>

	<div class="space"></div>

	<a class="block" href="/manage/check-in">
		<article>
			<h2><i>local_activity</i> Check-in Tickets</h2>
			<div class="row right-align">
				<i>arrow_forward</i>
			</div>
		</article>
	</a>

	<div class="space"></div>
</section>

<style>
	article h2 {
		font-size: 2em;
	}
</style>

// app/routes/manage.tsx
import { define } from '$lib/utils.ts';
import { supabase } from '$lib/supabase.ts';
import { User } from '@supabase/supabase-js';
import { Banner } from '$components/Banner.tsx';
import { PageMetadata } from '$components/PageMetadata.tsx';

export const handler = define.handlers<User | null>({
	async GET(_ctx) {
		const { data: { user }, error } = await supabase.auth.getUser();
		if (error) throw error;

		console.log("Manage>", "User is logged in:", user?.id);
		return { data: user };
	},
});

export default define.page<typeof handler>(function ManagementHomePage(props) {
	const username = props.data?.email ?? 'User';

	return (
		<>
			<PageMetadata title='Management Home' />
			<Banner title={`Welcome back, ${username}`} description='Manage ITea Lab events and Tradao tickets here' />

			<section style={{ maxWidth: '90ch', margin: 'auto' }}>
				<a className='block' href='/manage/events'>
					<article>
						<h2 style={{ fontSize: '2em' }}>
							<i>event</i> Manage Events
						</h2>
						<div className='row right-align'>
							<i>arrow_forward</i>
						</div>
					</article>
				</a>

				<div className='space'></div>

				<a className='block' href='/manage/tickets'>
					<article>
						<h2 style={{ fontSize: '2em' }}>
							<i>local_activity</i> Manage Tickets
						</h2>
						<div className='row right-align'>
							<i>arrow_forward</i>
						</div>
					</article>
				</a>

				<div className='space'></div>

				<a className='block' href='/manage/check-in'>
					<article>
						<h2 style={{ fontSize: '2em' }}>
							<i>check</i> Check-in via Ticket QR code
						</h2>
						<div className='row right-align'>
							<i>arrow_forward</i>
						</div>
					</article>
				</a>
			</section>
		</>
	);
});
