// app/src/components/TextClock.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { formatDate } from '$lib/utils';

	let time = $state(new Date());
	let interval: ReturnType<typeof setInterval>;

	onMount(() => {
		interval = setInterval(() => {
			time = new Date();
		}, 1000);
	});

	onDestroy(() => {
		if (interval) clearInterval(interval);
	});
</script>

<span>
	<i class="prefix-icon">schedule</i>
	<span>
		{formatDate(time, {
			hour: '2-digit',
			minute: '2-digit',
			hour12: false
		})} &bull;
		{formatDate(time, {
			weekday: 'short',
			day: '2-digit',
			month: 'short'
		})}
	</span>
</span>

// app/islands/TextClock.tsx
import { useEffect } from 'preact/hooks';
import { useSignal } from '@preact/signals';
import { formatDate } from '$lib/utils.ts';

export function TextClock() {
	const time = useSignal(new Date());

	useEffect(() => {
		const interval = setInterval(() => {
			time.value = new Date();
		}, 1000);
		return () => clearInterval(interval);
	}, []);

	return (
		<span>
			<i className='prefix-icon'>schedule</i>
			<span>
				{formatDate(time.value, {
					hour: '2-digit',
					minute: '2-digit',
					hour12: false,
				})} &bull; {formatDate(time.value, {
					weekday: 'short',
					day: '2-digit',
					month: 'short',
				})}
			</span>
		</span>
	);
}
